#!/bin/bash
set -e

# Create the user and group if the don't exist
grep -q "^cruise:" /etc/group || groupadd cruise
grep -q "^cruise:" /etc/passwd || useradd -d /var/spool/cruisecontrol -g cruise cruise

# Set the perms for cruise stuff
chown -R cruise:cruise /var/cache/cruisecontrol
chown -R cruise:cruise /var/spool/cruisecontrol
chown -R cruise:cruise /var/log/cruisecontrol
chown -R cruise:cruise /etc/cruisecontrol
chown cruise:cruise /etc/default/cruisecontrol
chown cruise:cruise /var/run/cruisecontrol.pid

# Set the perms for root stuff
chown -R root:root /usr/share/cruisecontrol
chown -R root:root /usr/share/doc/cruisecontrol
chown root:root /etc/init.d/cruisecontrol
chown root:root /etc/logrotate.d/cruisecontrol
chown root:root /usr/bin/cruisecontrol

